### DISCUSSION TITLE
Chrome taking the wrong source, what am I doing wrong?

### DISCUSSION THREAD

**Discussion by arbesulo** [rbuchberger/jekyll_picture_tag#284] [Q&A]
Hi! I'm totally new to responsive images.

I've been reading the documentation of JPT (very good by the way) and the MDN article linked from it (and some extras regarding the `source` and its attributes).

I'm building a site with bootstrap, so I defined the same breakpoints and added a preset for the home page as follows

```yaml
# _data/picture.yml

media_queries:
  xs: 'min-width: 0px'
  sm: 'min-width: 576px'
  md: 'min-width: 768px'
  lg: 'min-width: 992px'
  xl: 'min-width: 1200px'
  xxl: 'min-width: 1400px'

presets:
  home:
    dimension_attributes: true
    formats: [webp, original]
    widths: [367, 457, 490]
    sizes:
      xs: 367px
    size: 457px
```

For testing my issue, I am intentionally only defining `xs` under `sizes` and the default size.

The picture rendering can't be simpler:

```
{% picture home home.jpg %}
```
The generated html is:

```html
<head>
  ...
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  ...
</head>

<body>
...
<picture>
  <!-- formatted for readability, every tag is one line -->
  <source 
    sizes="(min-width: 0px) 367px, 457px"
    srcset="/assets/images/generated/home-367-61fbb2b73.webp 367w,
            /assets/images/generated/home-457-61fbb2b73.webp 457w,
            /assets/images/generated/home-490-61fbb2b73.webp 490w"
    type="image/webp">
  <source 
    sizes="(min-width: 0px) 367px, 457px"
    srcset="/assets/images/generated/home-367-e304c5499.jpg 367w,
            /assets/images/generated/home-457-e304c5499.jpg 457w,
            /assets/images/generated/home-490-e304c5499.jpg 490w" 
    type="image/jpeg">
  <img src="/assets/images/generated/home-800-e304c5499.jpg" width="2048" height="1365">
</picture>
...
<body>
```

When I inspect in chrome (in any viewport width), it is using `/assets/images/generated/home-490-61fbb2b73.webp` as current source.

I have 2 questions regarding this result:
1.- (The obvious one) Shouldn't Chrome be using `/assets/images/generated/home-367-61fbb2b73.webp`?
2.- Shouldn't JPT be setting the image with width=457px as the default one? Why does it set the one with width=490px?

Any help would be very appreciated.
Thanks in advance!
