### DISCUSSION TITLE
How does the "format" tag work?

### DISCUSSION THREAD

**Discussion by cortix** [rbuchberger/jekyll_picture_tag#290] [Q&A] [answered]
I'm wondering how the `format` tag works in the background. For example we have a preset like below;

**picture.yml**
```
presets:
  default:
    markup: data_auto
    formats: [webp, original] 
    widths: [200, 400, 800, 1200, 1600] 
    media_widths:
      mobile: [200, 400, 600]
      tablet: [400, 600, 800]
    noscript: true
    sizes:
      mobile: calc(100vw - 16px)
      tablet: 80vw

    fallback_width: 800
    fallback_format: original
    size: 800px
    link_source: false 
    dimension_attributes: true 

    attributes:
      parent: 'data-downloadable="true"'
      picture: 'data-volume="11" data-sizes="auto" class="lazyload"'
      img: 'data-sizes="auto" class="lazyload"'
      a: 'class="image-link"'

  webp:
    formats: [webp, original]
    markup: data_picture
    noscript: true
    .....
```

And suppose we are using `default` preset. Inside in the `default` preset, we have `format` setting. Here, inside the `format` tag, we are using `webp`. Does it mean that we should use the `webp` preset in `picture.yml`? I mean, does it refer to this -->

```
presets:
  default:
    ....
    ....
  webp:
    formats: [webp, original]
    markup: data_picture
    noscript: true
    .....
```

Or does it use the settings in `default` even though it's `webp`?

Thanks in advance.
