### ISSUE TITLE
Custom class attributes for the source tags

### ISSUE THREAD

**Issue by kylekirkby** [rbuchberger/jekyll_picture_tag#151]
Hi @rbuchberger,

Is it possible to add a custom class to the source tags in the generated HTML output? I'm looking to lazy load an Owl Carousel with multiple image sources and they require this format:

```html
  <picture>
      <source class="owl-lazy" media="(min-width: 650px)" data-srcset="https://placehold.it/350x250&text=3-large">
      <source class="owl-lazy" media="(min-width: 350px)" data-srcset="https://placehold.it/350x250&text=3-medium">
      <img class="owl-lazy" data-src="https://placehold.it/350x250&text=3-fallback" alt="">
  </picture>
```
Ref: [https://owlcarousel2.github.io/OwlCarousel2/demos/lazyLoad.html](https://owlcarousel2.github.io/OwlCarousel2/demos/lazyLoad.html)
Is this possible with the current features? I couldn't see it docs :) 

Best regards,

Kyle

**Comment by rbuchberger** [comment]
Yes! You're looking for the HTML attribute setting in 'writing presets'. Basically in _data/picture.yml you want something like:

```yml
markup_presets:
  owl-carousel:
    markup: data_picture
    noscript: true
    attributes:
      source: class="owl-lazy"
      img: class="owl-lazy"
```

And then use it with

`{% picture owl-carousel myimage.jpg %}`
