### ISSUE TITLE
Allow attributes to be specified for <a> tags

### ISSUE THREAD

**Issue by micahbf** [rbuchberger/jekyll_picture_tag#152]
It would be helpful for me if under `markup_presets`, I could define attributes that would be added to the `a` tags added by the `link_source` option.

My use case is that I want to add a margin specifically between adjacent images, doing something like:

```css
.blog-image + .blog-image {
  margin-top: 1em;
}
```

But since the images are wrapped in `a` tags which lack anything that I can select them with, I can’t do this.
