### ISSUE TITLE
Classes specified in an unrelated `picture` tag are mysteriously showing up in other picture tags

### ISSUE THREAD

**Issue by jeffblake** [rbuchberger/jekyll_picture_tag#153]
If I have

`{% picture half_lazy image.png --img class="test" %}`

And later (in the same file or even a different file):

`{% picture half_lazy another.png  %}`

The `another.png` tag outputs the class `test` used in the above unrelated picture tag. I'd expect it to use the default `img-fluid lazyload` class from the `picture.yml`

Here is my `picture.yml`

```
markup_presets:

  hero:
    markup: auto
    widths: [400, 600, 800, 1400]
    formats: [webp, original]
    attributes:
      img: 'class="img-fluid"'

  hero_lazy:
    markup: data_auto
    widths: [400, 600, 800, 1400]
    formats: [webp, original]
    attributes:
      img: 'class="img-fluid lazyload"'
    noscript: true


  half:
    widths: [200,400,600,1000]
    markup: auto
    formats: [webp, original]
    attributes:
      img: 'class="img-fluid"'

  half_lazy:
    widths: [200,400,600,1000]
    markup: data_auto
    formats: [webp, original]
    attributes:
      img: 'class="img-fluid lazyload"'
    noscript: true
```
