### ISSUE TITLE
markup: direct_url

### ISSUE THREAD

**Issue by rowanflack** [rbuchberger/jekyll_picture_tag#174]
RE: markup: direct_url
Issue with outputting generated image and url. 

RE: steps to reproduce
If I add a new image to the front-matter it won't trigger the markup_preset and generate the new image. However it will return the correct url.

If I change the name of the markup_preset and save, it will rebuild and trigger the markup_preset and output the new image.

Are you replicate and confirm this issue?

RE: _data/picture.yaml
media_presets:
  mobile: 'min-width: 768px'
markup_presets:
  default:
    markup: data_auto
    formats: [webp, original]
    widths: [480, 768, 1024, 1440]
    sizes:
      mobile: 60vw, 100vw
    attributes:
      img: 'class="img lazyload"'
  direct-url:
    markup: direct_url
    fallback_format: original
    fallback_width: 800

**Comment by rbuchberger** [comment]
I'm sorry, I don't entirely understand what you're trying to do. How are you using the front-matter image?

**Comment by rowanflack** [comment]
Sorry I wasn't sure if I'd been entirely clear. 

Front matter looks like this
testimonial:
 - image: lorum_ipsum.jpg
   heading: Lorum ipsum
 - image: blank.jpg
   heading: Blank

If i add a new entry (image and heading) to the above list or update an existing image it doesn't trigger the image generation of the direct-url markup preset above. 

However it does output the URL but the new/updated image is never generated.

HTML:
 {% picture direct-url {{ entry.image }} %}

**Comment by rbuchberger** [comment]
Ok, thanks! I'll look into this and see if I can reproduce it.

**Comment by kslstn** [comment]
Same here: no generated images for includes with these presets:

```
markup_presets:

  twitter-card:
    markup: direct_url
    formats: [original]
    fallback_width: 1024

  open-graph-size-l:
    markup: direct_url
    formats: [original]
    fallback_width: 1400

  open-graph-size-m:
    markup: direct_url
    formats: [original]
    fallback_width: 400
```
This used to work before.
