### ISSUE TITLE
Empty source tag as paragraph will generated

### ISSUE THREAD

**Issue by thorque** [rbuchberger/jekyll_picture_tag#175]
Hej,

sounds curious, or? 
I habe defined such a configuration:
```yaml
markup_presets:
  [...]
  gallery:
    formats: [webp, original]
    widths: [600]
    link_source: true
    relative_url: true`
```
and get this:
```html
<picture>
  <source srcset="smart-keyboard-folio-2-600-4f9aca.webp 600w" type="image/webp">
  <source srcset="smart-keyboard-folio-2-600-4f9aca.jpg 600w" type="image/jpeg">
  <img src="smart-keyboard-folio-2-800-4f9aca.jpg" alt="...">
  </source></source>
</picture>
```

In my Markdown I have such a line:
`{% picture gallery img.jpg --alt Blabla %}`

This empty source tag I don't understand what the reason is to get generated. The real problem is that is html encoded so its visible in the generated website. Can you give me a hint? Do I misconfigured something?

Thanks 
Thorsten
