### ISSUE TITLE
Images get regenerated

### ISSUE THREAD

**Issue by J370** [rbuchberger/jekyll_picture_tag#181]
Every time I do a build, the images gets generated again despite already existing in the generated folder.

**Comment by rbuchberger** [comment]
Thanks for the bug report! Can you give me a little more information?

**Comment by J370** [comment]
Sure, may I know what are the details required?

**Comment by rbuchberger** [comment]
Just details about how you're using it. You're the first one to report this issue and I haven't encountered it in my testing, so in order to figure out what's happening I need to work out what's different in your situation. 

Useful stuff would include:
- Any relevant configuration; `_config.yml` and `_data/picture.yml`
- Are you using a theme or anything, or did you start from scratch? 
- What other plugins are you using? 
- Does it happen for all picture tags or just some?
- If the relevant project is on github or something, a link to that would be helpful as well.

Thanks!

**Comment by J370** [comment]
Here are the requested items:

- `_config.yml`:
  ```
  picture:
    nomarkdown: false
    fast_build: true
  ```

  `_data/picture.yml`:
  ```
  markup_presets:
    default:
      formats: [webp, original]
      widths: [200, 400, 800, 1600]
      link_source: true
    lazy:
      markup: data_auto
      formats: [webp, original]
      widths: [200, 400, 800, 1600]
      noscript: true
      attributes: 
        img: class="lazy"
    icon:
      formats: [webp, original]
      base_width: 125
      pixel_ratios: [1, 1.5, 2]
      fallback_width: 150
      attributes:
      img: 'class="icon"'
  ```

- I am using two themes namely [Mediumish](https://github.com/wowthemesnet/mediumish-theme-jekyll/) and [Agency](https://github.com/y7kim/agency-jekyll-theme)

- Here is a list of the plugins I am using:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-minifier
  - jekyll-archives
  - jekyll-time-to-read
  - jekyll-last-modified-at
  - jekyll-multiple-languages-plugin

- It happens to all the picture tags

- I had sent you a request on GitHub to collaborate in the project.

Thank you so much for your help!
