### ISSUE TITLE
Enhancement: Image quality per size

### ISSUE THREAD

**Issue by kslstn** [rbuchberger/jekyll_picture_tag#203]
Before I knew how to use tools like this, I just used one high res JPEG for all dimensions and compressed the hell out of it. At 2x and 3x, you really don’t need a lot of detail (gradient banding can become an issue though). I just realized I could still compress my image for high pixel density screens a lot more and decrease load times. But that would reduce the quality on low pixel density screens below acceptable. 

A nice to have setting would be where for each size the quality could be set.

This would get finicky to define, as we’d have to define it for all formats in the preset. If this enhancement is considered, I’d be happy to come up with ideas for the syntax.

**Comment by rbuchberger** [comment]
That's a fantastic idea! I'll have to think on it a bit, but I don't think it should be too difficult to implement. 

I could see maybe instead of giving widths as an array, instead give them as key-value pairs? Something like:

```yml

widths:
    100: 25
    200: 50
    500: 100 
```
That, or maybe a global setting where you give formats, size ranges, and qualities. You're right, that syntax would get pretty intricate, though.

Sorry it took me so long to reply, I had other stuff going on that took priority.

**Comment by kslstn** [comment]
So I was thinking about this and how I already find it difficult to keep track of all the `widths` that a preset needs when optimizing for various breakpoints.

I always like it when computers calculate things for me, so maybe this would work:
```
media_queries:
  a: max-width: 479px
  b: min-width: 480px

presets:
  my_preset:
    auto_widths:
      a: 200-400 # Meaning 200 to 400 pixels wide (CSS measure, not actual image pixels)
      b: 600 # Meaning fixed 500px (CSS measure, not actual image pixels)
    pixel_densities: [1, 2, 2.5, 3] # This is used to calculate the image dimensions for the sizes required to support the auto_widths
    auto_qualities: [85, 40, 40, 30] # These values are mapped to the pixel densities. If there are not enough values, the latest is repeated. If there are too many, they are ignored.
```
Some assumptions have to be made about what image dimensions are needed to show a picture that can vary in size from 200–400 pixels wide. We could say something like for every 50% additional flexible width of an image, a new 'size' is added: 200, 300, 400, in this case.
    
No problem about the delay, I'm not in a hurry :)
