### ISSUE TITLE
Compress Images with Lossless Compression

### ISSUE THREAD

**Issue by ravgeetdhillon** [rbuchberger/jekyll_picture_tag#206]
I am trying to compress images but the resulting Webp images are bad in quality.

My JPT settings are:
```yml
format_quality:
  jpg: 100
  png: 100
  webp: 100

presets:
  blog_banner:
    widths: [20, 32, 64, 128, 300, 360, 484, 576, 720, 960, 1140, 1400]
    formats: [webp, original]
```

The way I compress the image manually using cwebp
```bash
cwebp -q 100 -lossless input.png -o output.webp
```

[Original Image](https://ibb.co/C0vqpNx)
[Image Compressed by JPT](https://ibb.co/pzsM3kL)
[Image Compressed Manually using cwebp](https://ibb.co/pXQDWTX)

You can clearly see that the quality of the image compressed by JPT is poor but by adding lossless compression we get a much better image. Is there an option to provide to do lossless compression?
