### ISSUE TITLE
Using picture_tag with i18n

### ISSUE THREAD

**Issue by VladyslavL** [rbuchberger/jekyll_picture_tag#211]
When I'm using some of i18n implementation, where almost whole website content is dublicated to another folder, all images become broken, because jekyll_picture_tag use relative url and adds locale prefix to src. 

For example: 
I'm using `jekyll-multiple-languages-plugin` with the next config: 
```
languages:
  - en
  - no

exclude_from_localizations:
  - _posts
  - new
  - img
  - uploads
  - css
  - js
  - video
  - fonts
```

Picture_tag config:
```
picture:
  output: assets
  ignore_missing_images: true
  suppress_warnings: true
  fast_build: development

```
These config means that my Norway website version placed inside `_site/no` folder. Picture_tag generates url with `no/` preffix that make my all images broken inside Norway version, because there no assets folder inside `/no` folder. There's no way to use two folder for output (for example — `output: [assets, no/assets]`) or use avoid of using relative url
