### ISSUE TITLE
Liquid exception: No such file or directory

### ISSUE THREAD

**Issue by stuntbox** [rbuchberger/jekyll_picture_tag#22]
Keep getting the following Liquid exception when trying to use this plugin: 

`Liquid Exception: No such file or directory - identify in _posts/2013-10-13-test.md`

Meanwhile, in my test post I'm using the simplest possible version of the tag: 

`{% picture a-test.jpg %}`

Relevant part of config as follows (lifted directly from project example): 

```
pygments: true
markdown: redcarpet

picture:
  source: bucket
  output: bucket/generated
  markup: picturefill
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 700
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
        height: 200
```

The source image is definitely in the `/bucket` directory. 

Hoping this is just some simple, bone-headed oversight on my part, but could use a hand chasing it down. Thanks!
