### ISSUE TITLE
Media queries and image widths

### ISSUE THREAD

**Issue by datapolitical** [rbuchberger/jekyll_picture_tag#237]
how do you use JPT to serve properly sized images, because I thought I was offering all the options but Google says my images are too big.

[Lighthouse results](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.chrisfnicholson.com%2Frecipes%2F) 

it sounds like I need multiple presets and different tags so the images render different on the main recipe page vs the individual recipe pages, but I don’t understand how they work together.

**Comment by datapolitical** [comment]
The examples.md page was helpful once I was able to find it.

**Comment by rbuchberger** [comment]
A preset is just a named collection of settings, allowing you to do exactly what you're describing: use different settings in different places. 

A prerequisite for writing presets is to understand responsive images in general, so make sure you have a good understanding of that. Did you read through the main [presets page](https://rbuchberger.github.io/jekyll_picture_tag/users/presets/)? It has links to some pretty good guides on the subject. Unless your images are close to the width of the viewport, it's important to create a [sizes attribute](https://rbuchberger.github.io/jekyll_picture_tag/users/presets/width_srcsets.html#sizes) as well.

I'm sorry this is giving you so much trouble; responsive images are surprisingly tricky and there is a limit to what I can have my plugin automate.

**Comment by datapolitical** [comment]
No don’t get me wrong, the plugin is great. And after tinkering with it for an hour I was able to write a config file that delivered the right sizes.

What’s missing is docs language that give examples not written for a technical audience. I shouldn’t have to study this hard to make this tool do what I want. My use case is simple enough that it should probably exist in the docs.

I still don’t exactly understand how I’m supposed to tell the browser to use a small image in some cases but not others, but this seemed to work so I went with it.

Like why do I even need to write media queries, don’t most people use the same ones cause we’re all dealing with the same browsers?

why would I ever not want dimension attributes to be true?

Some better examples explained in laymen’s terms would, I think, save others a lot of headache. 

I know you think the right move is pointing people to explainers on responsive images, but even most complex plugins don’t require that. 

You’ve built this great tool; the right thing to do is make it user friendly for the many Jekyll users who don’t know much about web design.

I have a decently good sense at this point in my life as to how hard something should be, and your docs were harder to understand than they should have been, was my primary point. It felt like a treasure hunt rather than a guided tour.

—

media_queries:
  mobile: "max-width: 600px"
  desktop: "min-width: 601px"
  ultrawide: "min-width: 1400px"

presets:
  default:
    widths: [280, 360, 400, 600, 800, 1000]
    formats: [webp, original]

    dimension_attributes: true
    attributes:
      img: class="photo"
    sizes:
      mobile: 90vw
      desktop: 50vw
    size: 500px

  lazy:
    formats: [webp, original]
    widths: [280, 360, 400, 600]
    dimension_attributes: true
    attributes:
      img: class="lazy photo-large"
    sizes:
      mobile: 90vw
      desktop: 30vw
    size: 300px

  drinks:
    widths: [280, 360, 400, 600, 800, 1000]
    formats: [webp, original]

    dimension_attributes: true
    sizes:
      desktop: 50vw
      mobile: 90vw
    size: 400px

**Comment by datapolitical** [comment]
For example, there’s no troubleshooting page that has common questions like “why is my browser picking a larger image than I need?” And some tips explaining how to fix that in simple English.

**Comment by rbuchberger** [comment]
I have been meaning to add some more examples and how-to guides, but I think you don't understand how complicated responsive images are. Layouts, screens, devices, browsers, and build environments have huge variation. I can make the defaults as good as possible, but there's no possible way to write a set of defaults that covers a majority of use-cases. The defaults are meant to get you up and running with a basic image srcset, and minimize unexpected behavior. Adding responsive images falls into squarely into proper web development territory; all a plugin does is automate the tedious bits. I'll concede that I should clarify this in the docs; I can see how 'easy responsive images for jekyll' might give the wrong impression.

* There are no standard media queries that everyone uses to tell the difference between mobile and desktop. Every layout is different. I can add some reasonable built-in ones, though. Look for it in v2, which I'll try to have out in the next few weeks. 
* If I set `dimension_attributes: true` by default, images which don't either have `width: auto` or `height: auto` applied in CSS will be stretched. If someone has to turn it on manually, then they know what it's doing and what the caveats are; if you install the plugin and are getting stretched images you'll likely have no idea what's causing it. It's harder to troubleshoot.

I guess I'm trying to say this is hard because responsive images are hard. Try doing it manually and you'll get the idea.

Also, I'd really appreciate help with improving the docs. I'll certainly take your feedback and implement what I can, but I only have so much time to put into this project. Pull requests are highly encouraged.

**Comment by datapolitical** [comment]
I'm still having this issue. I'm trying to configure this page https://www.chrisfnicholson.com/recipes/ to display a grid of images that can be up to four pictures wide, and unfortunately it's loading images that are much too large for the space provided. So on a desktop, instead of the 280w option (which is what web-inspector tells me the image should be) the browser is choosing a 600w image.

Can you just look at my preset and tell me what I'm doing wrong? I've been reading the links provided in the documentation but it just doesn't translate. I know I'm basically there but there's something wrong with what I'm putting in for sizes and how that relates to media queries.

(the preset being used is the "lazy" one)

Thanks!

Chris
```
media_queries:
  mobile: "max-width: 600px"
  desktop: "min-width: 601px"
  ultrawide: "min-width: 1400px"

presets:
  default:
    widths: [280, 360, 400, 600, 800, 1000]
    formats: [webp, original]

    dimension_attributes: true
    attributes:
      img: class="photo"
    sizes:
      mobile: 90vw
      desktop: 50vw
    size: 500px

  lazy:
    formats: [webp, original]
    widths: [280, 360, 400, 600]
    dimension_attributes: true
    attributes:
      img: class="lazy photo-large"
    sizes:
      mobile: 90vw
      desktop: 15vw
    size: 300px

  drinks:
    widths: [280, 360, 400, 600, 800, 1000]
    formats: [webp, original]

    dimension_attributes: true
    sizes:
      desktop: 50vw
      mobile: 90vw
    size: 400px
```
