### ISSUE TITLE
Stray end tag </source>

### ISSUE THREAD

**Issue by vosaul** [rbuchberger/jekyll_picture_tag#255]
Hello Robert
Thank you for your great work!

I tried to use jekyll_picture_tag 2.0.3 and I'm having this problem - when I specify 2 source formats, for some reason closing tags are generated </source> which causes a validation error.

```
media_queries:
  small: 'max-width: 424px'
  mobile: 'min-width: 425px'
  tablet: 'min-width: 768px'
  laptop: 'min-width: 1024px'
  desktop: 'min-width: 1440px'
presets:
  about:
    formats: [webp, original]
    widths: [220, 234, 287, 354]
    sizes:
      small: 220px
      mobile: 234px
      tablet: 287px
      laptop: 354px
    attributes:
      img: 'loading="lazy" width="3" height="2" style="width: 100%; height: auto"'
```

result:

```
 <picture>
    <source
      sizes="(max-width: 424px) 220px, (min-width: 425px) 234px, (min-width: 768px) 287px, (min-width: 1024px) 354px"
      srcset="/generated/user/img/about/angelica-220-55f4cc59d.webp 220w, /generated/user/img/about/angelica-234-55f4cc59d.webp 234w, /generated/user/img/about/angelica-287-55f4cc59d.webp 287w, /generated/user/img/about/angelica-354-55f4cc59d.webp 354w"
      type="image/webp">
    <source
      sizes="(max-width: 424px) 220px, (min-width: 425px) 234px, (min-width: 768px) 287px, (min-width: 1024px) 354px"
      srcset="/generated/user/img/about/angelica-220-d6125d2c9.jpg 220w, /generated/user/img/about/angelica-234-d6125d2c9.jpg 234w, /generated/user/img/about/angelica-287-d6125d2c9.jpg 287w, /generated/user/img/about/angelica-354-d6125d2c9.jpg 354w"
      type="image/jpeg">
    <img loading="lazy" width="3" height="2" style="width: 100%; height: auto"
      src="/generated/user/img/about/angelica-672-d6125d2c9.jpg" alt="Angelica">
    </source>
    </source>
  </picture>
```

validation:
![image](https://user-images.githubusercontent.com/28349676/120892884-f5c86d80-c618-11eb-8c9a-02132a75984c.png)

When I use the same code with jekyll_picture_tag 1.14.0 the correct code is generated.

**Comment by rbuchberger** [comment]
Hello! Thanks for the bug report. 

Is there some other processing happening after JPT? Are you running a normal Jekyll build with kramdown or something else? It looks to me like there's something which doesn't know about `<source>` tags is adding a closing tag because it thinks it's missing.

I can't reproduce this, and I can't think of a possible way that JPT would be doing it on its own.

**Comment by vosaul** [comment]
thanks for the quick response
the configuration is as follows:

Jekyll 4.0.1

_congig.yml:

```
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-regex-replace
  - jekyll-last-modified-at
  - jekyll-tidy
  - jekyll-target-blank
  - jekyll_picture_tag
  
target-blank:
   noreferrer: false
feed:
  tags: true
highlighter: rouge
```
Gemfile:

```
source "https://rubygems.org"

gem "jekyll", "~> 4.0.1"
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sitemap"
  gem "jekyll-regex-replace", "~> 1.1.0"
  gem "jekyll-last-modified-at"
  gem "jekyll-tidy"
  gem "jekyll-target-blank"
  gem 'jekyll_picture_tag', '~> 2.0'
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end
```

I will now try to check it out on the newly generated new Jekyll site
