### ISSUE TITLE
Linux and GitHub Actions

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [rbuchberger/jekyll_picture_tag#259]
I am using the `helaili/jekyll-action@v2` GitHub Action to deploy the site and I am getting this error:

```
 Dependency Error: Yikes! It looks like you don't have jekyll_picture_tag or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. If you've run Jekyll with `bundle exec`, ensure that you have included the jekyll_picture_tag gem in your Gemfile as well. The full error message from Ruby is: 'Could not open library 'glib-2.0.so.0': Error loading shared library glib-2.0.so.0: No such file or directory. Could not open library 'libglib-2.0.so.0': Error loading shared library libglib-2.0.so.0: No such file or directory' If you run into trouble, you can find helpful resources at jekyllrb.com/help/! 
``` 
Locally (Windows 10), it is working perfectly, but I am not sure why I have this error in GitHub.

I tried to install `glib-2.0` and/or `libvips` with no success.

**Comment by rbuchberger** [comment]
Huh... I think that's a problem with how jekyll-action is running things. Does it run `bundle install` and prefix `jekyll` with `bundle exec`?

**Comment by JavierSegoviaCordoba** [comment]
I fixed the problem because that specific action allow this:

```

      - name: Deploy
        uses:  helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pre_build_commands: |
            apk --update add vips vips-tools
```

It looks like all Jekyll actions haven't included in their docker instance the vips library, so even installing before running the action is useless.

It is lucky this action lets adding vips.
