### ISSUE TITLE
Resize not working as expected

### ISSUE THREAD

**Issue by mmeendez8** [rbuchberger/jekyll_picture_tag#277]
Hi, first of all thanks for such an amazing tool! This is definitely a complex topic but you provide a very interesting tutorials that have helped me to start with all this stuff!

I have been trying to do something quite simple but I am not really able to make it work. So I am wondering if there is something I am missing. I have a very simple grid layout with images and I am using `height: auto` and `width: 100%` so they fit to the parent container. I just want to serve the smallest image depending on my current layout. So following your docs I have created two simple media queries as a starting point. After that I added the widths list and I have set the sizes attribute as below:

```yaml
media_queries:
  mobile: "max-width: 767"
  desktop: "min-width: 768px"

  posts:
    formats: [webp, original]
    widths: [400, 600, 800, 1000]
    dimension_attributes: true
    attributes:
      img: 'loading="lazy"'
    sizes:
      mobile: calc(100vw - 38px)
      desktop:   461px
```
I thought this would be straightforward but is quite hard to debug since I do not really know what the browser is doing. When I select the "phone view" of the browser and check the network tab, it is downloading 1000 width images. Current displayed image is 350px width so I was expecting this to download the 400 width one. 

When I increase the viewport to a "desktop screen" (above 768px) only 800 widht images are downloaded. This is better although even smaller images could be selected since displayed image width is 461px.

This is the web I am trying to modify [https://mmeendez8.github.io/](https://mmeendez8.github.io/) I want to download appropriate image sizes for my Posts section.

Any advice will be welcome, thanks!
