### ISSUE TITLE
Problems with media_crop

### ISSUE THREAD

**Issue by ThomasTilch** [rbuchberger/jekyll_picture_tag#306]
Hi. I have problems using presets with different aspect ratios using media_crop in my presets. 
Just the crop-value is recognized. I really tried everything. But I know… I am doing something wrong. 
 
**My Preset**
```yaml
media_queries:
    mobile: 'max-width: 640px'
    desktop: 'max-width: 1920px'
presets:
  herobg:
    widths: [320, 1280]
    sizes: 
      mobile_s: 100vw 
      laptop: 100vw 
    crop: '1:1'
    media_crop:
      desktop: '1:2'
      mobile: '2:1'
```
**Template usage**
{% picture herobg _test-image_2560x980.jpg %}

But all Images are created in crop '1:1'

Perhaps someone could help me out.
