### ISSUE TITLE
FalseClass does not have #dig method in... Error

### ISSUE THREAD

**Issue by ecupaio** [rbuchberger/jekyll_picture_tag#320]
_config.yml

```
picture:
  source: "images"
  output: "images/generated"
  ignore_missing_images: true
  webp:
    format: webp
```

Gemfile
```
source "https://rubygems.org"
gem "jekyll", "4.2.0"
group :jekyll_plugins do
   gem 'jekyll-sitemap'
   gem 'jekyll_picture_tag', '~> 2.0'
end
```

ran bundle install
ran brew install vips

directory is images in root and added a generated folder within the images directory

added {% picture my-picture.jpg %} which exists in my images directory. 

I get the following error: `Liquid Exception: FalseClass does not have #dig method in [layout]`

I have no idea what is wrong. i just want webp and resized images...
