### ISSUE TITLE
Liquid Exception: no such file or directory

### ISSUE THREAD

**Issue by rask** [rbuchberger/jekyll_picture_tag#65]
I'm attempting to build my Jekyll project which will (I hope) use this picture tag plugin. I'm on Windows, latest Jekyll and latest version of the plugin.

When building I receive the following error:

``` sh
Generating image-360by248-abcdefg.jpg
  Liquid Exception: No such file or directory - identify -ping C:/Users/user/AppData/Local/Temp/mini_magick20150829-8176-87razr.jpg in _drafts/some-draft.md
        done.
```

(I ran with `--trace` but it gave no more information.)

My picture configuration:

``` yaml
picture:
    source: "_img"
    output: "img"
    markup: "picture"
    presets:
        default:
            ppi: [1, 1.5, 2]
            attr:
                class: "post-image-medium"
                itemprop: "image"
            source_large:
                media: "(min-width: 720px)"
                width: "360"
            source_medium:
                media: "(min-width: 480px)"
                width: "180"
            source_default:
                width: "120"
        post_large:
            ppi: [1, 1.5, 2]
            attr:
                class: "post-image-large"
                itemprop: "image"
            source_large:
                media: "(min-width: 720px)"
                width: "720"
            source_medium:
                media: "(min-width: 480px)"
                width: "480"
            source_default:
                width: "320"
        post_small:
            ppi: [1, 1.5, 2]
            attr:
                class: "post-image-small"
                itemprop: "image"
            source_large:
                media: "(min-width: 720px)"
                width: "240"
            source_medium:
                media: "(min-width: 480px)"
                width: "120"
            source_default:
                width: "80"
```

The `_drafts/some-draft.md` has a simple picture tag used with:

```
{% picture directory/image.jpg %}
```

And `jekyllsource/_img/directory/image.jpg` exists. When `jekyll serve --drafts --trace` is used the destination directory (`jekyllbuilt/img/directory`) is created but no contents (images) appear inside it.

The error pops up and the generated draft page is an totally empty HTML file.

I installed the plugin using a Gemfile (`bundle install`) and I copied the raw jekyll-picture-tag.rb to the Jekyll plugins directory too.

**Additional warns and notices in the output that I could find:**

`Unresolved specs during Gem::Specification.reset` appears for _redcarpet_ and _listen_.

Could these have anything to do with the error?
